#! /bin/sh

# start programs (started with xfce startup apps)
# sxhkd &
# compton --config ~/.config/compton.conf &
# nitrogen --restore

# setup workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# looks
ACCENT="#5294E2"
bspc config border_width		4
bspc config active_border_color		$ACCENT
bspc config focused_border_color	$ACCENT
bspc config presel_feedback_color	$ACCENT

bspc config window_gap			12

# default splitting behavior
bspc config split_ratio			0.5
bspc config initial_polarity		second_child
bspc config automatic_scheme		longest_side

# if only one node, use monocle layout, and turn off the border
bspc config single_monocle       	true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false

bspc config pointer_modifier 		mod4
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_corner

# specific window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# kde specific rules
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off rectangle=1000x100+0+900
bspc rule -a 'plasmashell:*' state=floating

# xfce specific rules
bspc rule -a "Wrapper-2.0" state=floating border=off

