#! /bin/sh

# start programs
sxhkd &
compton --config ~/.config/compton.conf &

# setup workspaces
bspc monitor -d I II III IV V VI VII VIII IX

# looks
MANJARO_GREEN="#1abc9c"
bspc config border_width		6
bspc config active_border_color		$MANJARO_GREEN
bspc config focused_border_color	$MANJARO_GREEN
bspc config presel_feedback_color	$MANJARO_GREEN

bspc config window_gap			12
bspc config bottom_padding		60
bspc config top_padding			30

# default splitting behavior
bspc config split_ratio			0.5
bspc config initial_polarity		second_child
bspc config automatic_scheme		longest_side

# if only one node, use monocle layout, and turn off the border
bspc config single_monocle       	true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false

bspc config pointer_modifier 		mod4
bspc config pointer_action1 		resize_side
bspc config pointer_action2 		resize_corner

# specific window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# kde specific rules
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off rectangle=1000x100+0+900
bspc rule -a 'plasmashell:*' state=floating

